# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章標題')),
                ('category', models.CharField(max_length=20, verbose_name='文章分類')),
                ('limit', models.CharField(max_length=10, verbose_name='文章權限')),
                ('introduce', models.CharField(max_length=90, verbose_name='文章簡介')),
                ('content', models.TextField(verbose_name='文章內容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
