# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='用戶姓名')),
                ('nickname', models.CharField(max_length=30, verbose_name='綽號')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='信箱')),
                ('password', models.CharField(max_length=32)),
                ('sign', models.CharField(max_length=50, verbose_name='狀態消息')),
                ('info', models.CharField(max_length=150, verbose_name='自我介紹')),
                ('avator', models.ImageField(upload_to='avatar/')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
