# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-17 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=500, verbose_name='内容'),
        ),
    ]
